export type AppPage =
  | 'dash'
  | 'assets'
  | 'expenses'
  | 'minha_previdencia'
  | 'simulator'
  | 'evolution_assets'
  | 'courses'
  | 'course1'
  | 'course2'
  | 'course3'
  | 'previdencia_mod01'
  | 'wallets'
  | 'wallet1'
  | 'wallet2'
